### ISSUE TITLE
Using custom web-path...no JS?

### ISSUE THREAD

**Issue by SethAten** [dutchcoders/transfer.sh-web#1]
So, maybe this is just me, because there are no real docs, and I've made it as far as I have repairing errors(installing a ton of grunt reqs, bower update/install based on missing file errors) but when I get to the point that transfer.sh is using my web-path, it would seem the javascript isn't working? No drag/drop, buttons don't expand content, can't open upload browser, etc. 

Any ideas? Using transfer.sh without web-path works flawlessly, so not a browser issue, but then the page has all the wrong URLS for my instance.

**Comment by gclem** [comment]
UP

**Comment by gclem** [comment]
Fine for me,

Some steps to add, avoiding some boring fixes.

https://github.com/dutchcoders/transfer.sh-web/pull/2

**Comment by aspacca** [comment]
@SethAten @gclem , still an issue?

Can you try with latest master? (both tranfer.sh and transfer.sh-web)

**Comment by aspacca** [comment]
@SethAten , still relevant?
