### ISSUE TITLE
ambigous project, improve documentation: transfer.sh(-web) service/frontend ?

### ISSUE THREAD

**Issue by mckaygerhard** [dutchcoders/transfer.sh-web#16]
PRELIMINARY: the project transhfer.sh-web as pointed in #15  seems are a service  that depends on the original binary program client/backend, **as separate project that uses that program as a backend, seems documentation are very ambogous and not clear to many users** 

if something clafify for me those i can provide better documentation (stating at the wiki project and later after you can reviewed, i can provide a pull request with a better README):

1) the README seems does not clarify how its works, its said "the web frontend for ..." and make it feel like the binary compiled its a complete selft conatined binary that deploys all need for "transfer.sh" website, but does not said what are need for, inclusivelly seems the dependencies are external to...

2) the README does not point if the other project "transfer.sh" are a dependency, i mean, in examples are using the string "`dutchcoders/transfer.sh ...`" in the docker run command, but does not clarify that if need that project compiled and run in specific settings or now need that project...

3) also, the proyect are under same "team" (duchcoders) but seems (as i can see in the other) are "away" and "un-sync" of the development of the "transfer.sh" project, and out-of-sync

4) as pointed, compilation need external resources (need internet connection) so deploying in more specific service in intranet's are very complicated due missiing information about alternate methods...

**Comment by mckaygerhard** [comment]
please dont close until are in sync with dutchcoders/transfer.sh#183

**Comment by aspacca** [comment]
@mckaygerhard check dutchcoders/transfer.sh#183
