### ISSUE TITLE
Unable to preview on mobile, and annoying on desktop

### ISSUE THREAD

**Issue by notramo** [dutchcoders/transfer.sh-web#17]
The "**Don’t Panic! transfer.sh will live on! ...**" text hides the image or text preview on mobile.
What about only showing the title, and showing additional info on clicking? (`<details>` tag)
Also, if someone uses the service often, after reading the content of the yellow block first time, it becomes annoying, because it contains the same text which we know already.

**Comment by aspacca** [comment]
@notramo the alert is not part of this repository as you can check in the source code.
