### ISSUE TITLE
The sample transfer function didn't work with .bashrc

### ISSUE THREAD

**Issue by slurdge** [dutchcoders/transfer.sh-web#18]
When trying to use the provided function when queried without parameters in command line, I had the following error:
```. ~/.bashrc
-bash: /root/.bashrc: line 20: syntax error near unexpected token `;;'
```
It comes from the `"|tee /dev/null,;;`, I removed a ; and the function works correctly.

My zsh-fu is not good enough to know if it's required by zsh.

**Comment by aspacca** [comment]
@slurdge you are right (at least in bash), I'm not sure even about sone extra commas. I will fix the front-end as soon as I've time
