### ISSUE TITLE
Annoying note popup on mobile

### ISSUE THREAD

**Issue by kairusds** [dutchcoders/transfer.sh-web#22]
is this gonna be removed soon?
![img](https://camo.githubusercontent.com/058244dacafe0e3324a30252970c972d6e36c576/68747470733a2f2f7472616e736665722e73682f50733770322f53637265656e73686f745f32303139303431352d3036323931352e706e67)

**Comment by aspacca** [comment]
this repo doesn't have any connection to the service hosted on https://transfer.sh
sorry
