### ISSUE TITLE
Getting inline URL

### ISSUE THREAD

**Issue by Br31zh** [dutchcoders/transfer.sh-web#38]
Hello,

I’d like to add the inline URL in my custom download page, but there is no way to get just the random part of the string, nor the relative URL. I tried to do a replace on the get URL, but I didn’t find how it can be done (your templating seems a little bit more advanced than basic Go templating, but I didn’t found what is it).

Thanks.

**Comment by aspacca** [comment]
hi @Br31zh , I apologize for not having the time yet to document the custom frontend. it's plain go template anyway
but the url rendered from the upload form is not on the template: it comes from the response of the PUT ajax request

you have to change the javascript here: https://github.com/dutchcoders/transfer.sh-web/blob/master/src/scripts/base.js#L57

the `xhr.responseText` is something like `https://transfer.sh/eibhM/hello.txt`: you have to parse the url and add the `inline` path part

**Comment by Br31zh** [comment]
Yeah, I’ve tried that, but I can’t make a link to `/inline/eibhM/hello.txt`. If Url didn’t include scheme and hostname, I could build it with `{{ .WebAddress }}/inline/{{ .Url }}` but for now I can’t. And Go templating don’t seem to permit string replacement / cut.

**Comment by aspacca** [comment]
I will add `{{ .UrlRandomToken }}` to the backend

**Comment by aspacca** [comment]
https://github.com/dutchcoders/transfer.sh/pull/370

**Comment by Br31zh** [comment]
That’s perfect, thanks a lot.

**Comment by aspacca** [comment]
@Br31zh I'm going to rename `{{ .UrlRandomToken }}` to `{{ .URLRandomToken }}` due to go linting in master on the backend
