### ISSUE TITLE
The download page cannot be clicked on the footer.

### ISSUE THREAD

**Issue by wc7086** [dutchcoders/transfer.sh-web#43]
There is no response when you click the footer on the download page. When you double-click the footer, the focus is in the previous `<div>` tag. I checked the code, but couldn't find the problem.

![bug1](https://user-images.githubusercontent.com/74053663/129471129-4faafe8f-b890-4168-9472-45346de2d3bc.gif)

![bug2](https://user-images.githubusercontent.com/74053663/129472071-56974463-e31c-4544-a3ba-464cfb4314a6.gif)

**Comment by aspacca** [comment]
thanks @wc7086 it was already reported:
duplicates https://github.com/dutchcoders/transfer.sh/issues/358

Still had no time to check what is the problem.
Actually the whole footer needs a refactoring (removing bitcoin donation link etc, see the other issue)
