### ISSUE TITLE
Remove dependency on Google Fonts

### ISSUE THREAD

**Issue by antondollmaier** [dutchcoders/transfer.sh-web#52]
Hi folks,

as you perhaps have already seen in the news, a [court decision](https://www.golem.de/news/google-fonts-abmahnungen-an-webseitenbetreiber-mit-google-schriftarten-2208-167472.html) has made the use of hosted Google Fonts a legal issue.

For our own instance of transfer.sh, I've manually modified the frontend to simply remove the reference to fonts.googleapis.com - but this should not be the preferable way.

The folks at Cachet added a config flag ("enable 3rd party dependencies"), which - in the case of this frontend - is probably not so easy to implement (except for having two docker images?).

The best approach should be to simply include the fonts locally during build. I discovered that there is a [grunt package to copy the font](https://www.npmjs.com/package/grunt-google-fonts), but as I'm no developer myself, I'm unable to integrate it properly.

Thanks for considering this request for additional privacy!

Best,
Anton

**Comment by aspacca** [comment]
hi @antondollmaier , thanks for raising this issue

I will try to work on it as soon as possible
